[package]
name = "raw_terminal"
version = "0.1.0"
edition = "2021"
authors = ["ink-carp <18020970773@163.com>"]
license = "Apache 2.0 source=http://www.apache.org/licenses/LICENSE-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
